<?php

namespace App\Console\Commands;

use App\Services\Catalog\CourseFileScanner;
use App\Services\Catalog\YouTubeLinkChecker;
use Illuminate\Console\Command;

/**
 * Checks every YouTube link in the authored course files before any of it
 * reaches a student, and writes a report the owner can audit.
 *
 * Run before importing (a dead link must never become a lesson) and monthly
 * afterwards, because YouTube links rot: a video is made private, a channel is
 * reorganised, and the platform should notice before a student does.
 */
class VerifyCourseLinks extends Command
{
    protected $signature = 'courses:verify-links
        {--dir=course-content : Directory holding the authored course files}
        {--fresh : Ignore the cache and re-check every link}
        {--only= : Check a single file, e.g. 03-php-programming-step-by-step.md}';

    protected $description = 'Verify every YouTube video and playlist link in the course files';

    public function handle(CourseFileScanner $scanner): int
    {
        $directory = base_path((string) $this->option('dir'));

        if (! is_dir($directory)) {
            $this->error("No such directory: {$directory}");

            return self::FAILURE;
        }

        $cachePath = $directory.'/_link-cache.json';
        if ($this->option('fresh') && is_file($cachePath)) {
            unlink($cachePath);
        }

        $checker = new YouTubeLinkChecker($cachePath);

        $files = $scanner->files($directory);
        if ($only = $this->option('only')) {
            $files = $files->filter(fn ($f) => basename($f) === $only)->values();
        }

        if ($files->isEmpty()) {
            $this->error('No course files found.');

            return self::FAILURE;
        }

        $report = [];
        // Three states, not two. A live video with embedding switched off is
        // not a dead link and must never be repaired as if it were.
        $totals = ['checked' => 0, 'ok' => 0, 'noembed' => 0, 'dead' => 0, 'unreachable' => 0];

        foreach ($files as $path) {
            $heading = $scanner->heading($path);
            $references = $scanner->references($path);

            $this->line(sprintf('<info>%s</info> — %d link(s)', basename($path), count($references)));
            $bar = $this->output->createProgressBar(count($references));
            $bar->start();

            $rows = [];
            $seen = [];

            foreach ($references as $reference) {
                $key = $reference['type'].':'.$reference['id'];

                // The same video can legitimately appear twice in one file;
                // check it once and report it once per file.
                if (isset($seen[$key])) {
                    $bar->advance();

                    continue;
                }
                $seen[$key] = true;

                $result = $checker->check($reference['type'], $reference['id']);
                $totals['checked']++;

                if ($result['ok'] && $result['embeddable']) {
                    $totals['ok']++;
                } elseif ($result['ok']) {
                    $totals['noembed']++;
                } elseif ($result['reason'] === 'unreachable') {
                    $totals['unreachable']++;
                } else {
                    $totals['dead']++;
                }

                $rows[] = $reference + $result;
                $bar->advance();
            }

            $bar->finish();
            $this->newLine();

            $report[] = ['file' => basename($path), 'heading' => $heading, 'rows' => $rows];
        }

        $this->writeReport($directory.'/_link-report.md', $report, $totals);

        $this->newLine();
        $this->table(
            ['Checked', 'Embeddable', 'Watch-on-YouTube only', 'Gone', 'Unreachable'],
            [[$totals['checked'], $totals['ok'], $totals['noembed'], $totals['dead'], $totals['unreachable']]],
        );
        $this->info('Report written to '.str_replace(base_path().'/', '', $directory).'/_link-report.md');

        // A dead link is a finding to act on, not a crash — the report is the
        // deliverable. Only an unreachable network makes the run itself invalid.
        return $totals['unreachable'] > 0 ? self::FAILURE : self::SUCCESS;
    }

    /** @param list<array{file:string,heading:array,rows:list<array>}> $report */
    private function writeReport(string $path, array $report, array $totals): void
    {
        $out = [];
        $out[] = '# Course link verification report';
        $out[] = '';
        $out[] = sprintf(
            '%d links checked · **%d embeddable** · **%d watch-on-YouTube only** · **%d gone** · %d unreachable',
            $totals['checked'], $totals['ok'], $totals['noembed'], $totals['dead'], $totals['unreachable']
        );
        $out[] = '';
        $out[] = 'Generated by `php artisan courses:verify-links`.';
        $out[] = '';
        $out[] = '| | Meaning | What happens on import |';
        $out[] = '|-|---------|------------------------|';
        $out[] = '| ✅ | Live and embeddable | Plays inside the lesson player |';
        $out[] = '| ▶️ | Live, but the owner disabled embedding | Real teaching. The lesson links out to YouTube instead of showing a dead player |';
        $out[] = '| ❌ | Removed or private | Must be replaced with the right video, or rewritten as a text lesson |';
        $out[] = '';

        if ($totals['noembed'] > 0) {
            $out[] = '## Live, but not embeddable';
            $out[] = '';
            $out[] = 'These are real videos. They open on YouTube and are not to be replaced.';
            $out[] = '';
            $out[] = '| File | Line | Lesson | Id | Title on YouTube |';
            $out[] = '|------|-----:|--------|----|------------------|';
            foreach ($report as $file) {
                foreach ($file['rows'] as $row) {
                    if ($row['ok'] && ! $row['embeddable']) {
                        $out[] = sprintf('| %s | %d | %s | `%s` | %s |',
                            $file['file'], $row['line'], str_replace('|', '\|', $row['label'] ?: '—'),
                            $row['id'], str_replace('|', '\|', (string) $row['title']));
                    }
                }
            }
            $out[] = '';
        }

        if ($totals['dead'] > 0) {
            $out[] = '## Gone — these need a real repair';
            $out[] = '';
            $out[] = '| File | Line | Lesson | Id | Why |';
            $out[] = '|------|-----:|--------|----|-----|';
            foreach ($report as $file) {
                foreach ($file['rows'] as $row) {
                    if (! $row['ok'] && $row['reason'] !== 'unreachable') {
                        $out[] = sprintf('| %s | %d | %s | `%s` | %s |',
                            $file['file'], $row['line'], $row['label'] ?: '—', $row['id'], $row['reason']);
                    }
                }
            }
            $out[] = '';
        }

        foreach ($report as $file) {
            $out[] = '## '.$file['file'];
            $out[] = '';
            $gone = collect($file['rows'])->reject(fn ($r) => $r['ok'])->count();
            $noEmbed = collect($file['rows'])->filter(fn ($r) => $r['ok'] && ! $r['embeddable'])->count();
            $out[] = sprintf('%s — %d link(s), %d watch-on-YouTube only, %d gone.',
                $file['heading']['title'], count($file['rows']), $noEmbed, $gone);
            $out[] = '';
            $out[] = '| | Line | Lesson | Link | Title on YouTube |';
            $out[] = '|-|-----:|--------|------|------------------|';

            foreach ($file['rows'] as $row) {
                $out[] = sprintf('| %s | %d | %s | [%s](%s) | %s |',
                    $row['ok'] ? ($row['embeddable'] ? '✅' : '▶️') : '❌',
                    $row['line'],
                    str_replace('|', '\|', $row['label'] ?: '—'),
                    $row['type'] === 'playlist' ? 'playlist' : $row['id'],
                    $row['url'],
                    str_replace('|', '\|', $row['ok'] ? (string) $row['title'] : '**'.$row['reason'].'**'),
                );
            }
            $out[] = '';
        }

        file_put_contents($path, implode("\n", $out)."\n");
    }
}
